name: Build Passage library for iOS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ vars.XCODE_VERSION }}'

      - name: Caching Kotlin/Native tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build library
        run: ./gradlew ${{ matrix.target }}
